version: '3.4'

services:
  bookmarksmanager.api:
    image: ${DOCKER_REGISTRY-}bookmarksmanagerapi
    build:
      context: .
      dockerfile: BookmarksManager.Api/Dockerfile
    volumes:
      - "/db:/db"
    ports:
      - 5000:5000