version: '3.4'

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - /db:/db
  bookmarksmanager.api:
    image: ${DOCKER_REGISTRY-}bookmarksmanagerapi
    build:
      context: .
      dockerfile: BookmarksManager.Api/Dockerfile
    volumes:
      - /db:/db
    ports:
      - 5000:5000