// <auto-generated />
using BookmarksManager.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookmarksManager.Persistence.Migrations
{
    [DbContext(typeof(BookmarksManagerDbContext))]
    partial class BookmarksManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("BookmarksManager.Domain.Entities.BookmarkBar", b =>
                {
                    b.Property<string>("DateAdded")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("BookmarkBar");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Child", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncedId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("SyncedId");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.MetaInfo", b =>
                {
                    b.Property<string>("LastVisitedDesktop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MetaInfo");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Other", b =>
                {
                    b.Property<string>("DateAdded")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateModified")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Other");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Root", b =>
                {
                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncMetadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.ToTable("Root");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Roots", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.ToTable("Roots");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Synced", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Synced");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Child", b =>
                {
                    b.HasOne("BookmarksManager.Domain.Entities.Child", null)
                        .WithMany("Children")
                        .HasForeignKey("ChildId");

                    b.HasOne("BookmarksManager.Domain.Entities.Synced", "Synced")
                        .WithMany("Children")
                        .HasForeignKey("SyncedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Synced");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Child", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("BookmarksManager.Domain.Entities.Synced", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
